import type { Profile, Variety, Photo } from "./types";

/**
 * Встроенные демонстрационные данные.
 * Используются, когда Supabase не сконфигурирован (нет env-переменных),
 * чтобы MVP можно было запустить и показать одной командой.
 */

export const mockProfiles: Profile[] = [
  {
    id: "11111111-1111-1111-1111-111111111111",
    name: "Анна Гибискусова",
    city: "Краснодар",
    bio: "Селекционер гибискусов с 15-летним стажем. Специализируюсь на махровых формах.",
    avatar_url: "/seed/avatar-anna.svg",
  },
  {
    id: "22222222-2222-2222-2222-222222222222",
    name: "Игорь Тропиков",
    city: "Санкт-Петербург",
    bio: "Коллекционер тропических гибискусов. Люблю яркие огненные и махровые формы.",
    avatar_url: "/seed/avatar-igor.svg",
  },
];

/** Пустой паспорт — поля, которые сорт может не заполнять. */
const emptyPassport = {
  origin: null,
  pod_parent: null,
  pollen_parent: null,
  bloom_type: null,
  size_range: null,
  hybridizer: null,
  date_registered: null,
  grower: null,
  reg_mini: null,
  color_group: null,
  propagation: null,
  bloom_colors: null,
  photographer: null,
  pod_parent_registered: null,
  pollen_parent_registered: null,
  grower_same: null,
  vein_color: null,
  spots_color: null,
  eye_color: null,
  num_colors: null,
  color_rings: null,
  pad_color: null,
  bloom_form: null,
  bloom_features: null,
  petal_overlap: null,
  veining: null,
  substance: null,
  bloom_duration: null,
  presentation: null,
  eye_zone_size: null,
  prop_seedling: null,
  prop_pollen: null,
  prop_rooting: null,
  prop_performance: null,
  leaf_size: null,
  leaf_look: null,
  bush_development: null,
  bush_size: null,
  bush_width: null,
  bush_form: null,
};

export const mockVarieties: Variety[] = [
  {
    id: "aaaaaaa1-0000-0000-0000-000000000001",
    name: "Алый Закат",
    species: "Простой",
    breeder_id: "11111111-1111-1111-1111-111111111111",
    year_created: 2018,
    description: "Простой алый гибискус с крупными цветами до 18 см.",
    care_notes: "Яркий рассеянный свет, полив по подсыханию верхнего слоя.",
    main_photo_url: "/seed/alyy-zakat.svg",
    parent_a_id: null,
    parent_b_id: null,
    ...emptyPassport,
    origin: "Краснодар, Россия",
    bloom_type: "Простой обычный (немахровый)",
    size_range: "Крупный, 16–18 см",
    hybridizer: "Анна Гибискусова",
    date_registered: "2018-06-15",
    grower: "Анна Гибискусова",
    reg_mini: "Обычный (стандарт)",
    color_group: "Красная",
    bloom_colors: "Чистый алый основной цвет с тёмно-карминовым горлом и едва заметной светлой каймой по краю лепестка.",
  },
  {
    id: "aaaaaaa2-0000-0000-0000-000000000002",
    name: "Белая Ночь",
    species: "Простой",
    breeder_id: "11111111-1111-1111-1111-111111111111",
    year_created: 2019,
    description: "Кремово-белый гибискус с тонкой розовой жилкой.",
    care_notes: "Любит влажный воздух, опрыскивание в жару.",
    main_photo_url: "/seed/belaya-noch.svg",
    parent_a_id: null,
    parent_b_id: null,
    ...emptyPassport,
    origin: "Краснодар, Россия",
    bloom_type: "Простой обычный (немахровый)",
    size_range: "Средний, 12–14 см",
    hybridizer: "Анна Гибискусова",
    date_registered: "2019-07-02",
    grower: "Анна Гибискусова",
    reg_mini: "Обычный (стандарт)",
    color_group: "Белая",
    bloom_colors: "Кремово-белый основной цвет с тонкими розовыми прожилками, расходящимися от светло-жёлтого горла.",
  },
  {
    id: "aaaaaaa3-0000-0000-0000-000000000003",
    name: "Розовая Заря",
    species: "Махровый",
    breeder_id: "11111111-1111-1111-1111-111111111111",
    year_created: 2022,
    description:
      "Махровый гибрид с переходом от алого к кремовому. Гордость коллекции.",
    care_notes:
      "Регулярная подкормка в период цветения, формирующая обрезка весной.",
    main_photo_url: "/seed/rozovaya-zarya.svg",
    parent_a_id: "aaaaaaa1-0000-0000-0000-000000000001",
    parent_b_id: "aaaaaaa2-0000-0000-0000-000000000002",
    ...emptyPassport,
    origin: "Краснодар, Россия",
    pod_parent: "Алый Закат",
    pollen_parent: "Белая Ночь",
    bloom_type: "Махровый",
    size_range: "Очень крупный, 20–23 см",
    hybridizer: "Анна Гибискусова",
    date_registered: "2022-08-20",
    grower: "Анна Гибискусова",
    reg_mini: "Обычный (стандарт)",
    color_group: "Розовая",
    propagation: "Черенкование",
    bloom_colors: "Тёмно-бордовый глазок в центре, мелкие белые прожилки пронизывают розовый основной цвет с переходом от светлого к тёмному и жёлтой каймой по краю.",
  },
  {
    id: "aaaaaaa4-0000-0000-0000-000000000004",
    name: "Рассвет",
    species: "Махровый",
    breeder_id: "11111111-1111-1111-1111-111111111111",
    year_created: 2024,
    description:
      "Коралловый гибрид от «Розовой Зари» — родословная уходит на два поколения.",
    care_notes: "Светолюбив, подкормка раз в две недели в сезон.",
    main_photo_url: "/seed/rassvet.svg",
    parent_a_id: "aaaaaaa3-0000-0000-0000-000000000003",
    parent_b_id: "aaaaaaa1-0000-0000-0000-000000000001",
    ...emptyPassport,
    origin: "Краснодар, Россия",
    pod_parent: "Розовая Заря",
    pollen_parent: "Алый Закат",
    bloom_type: "Махровый",
    size_range: "Крупный, 17–19 см",
    hybridizer: "Анна Гибискусова",
    date_registered: "2024-05-30",
    grower: "Анна Гибискусова",
    reg_mini: "Обычный (стандарт)",
    color_group: "Коралловая",
    propagation: "Черенкование",
    bloom_colors: "Насыщенный коралловый основной цвет с золотистым свечением у горла и лёгким малиновым напылением к краю лепестков.",
  },
  {
    id: "bbbbbbb1-0000-0000-0000-000000000001",
    name: "Огненный Вихрь",
    species: "Полумахровый",
    breeder_id: "22222222-2222-2222-2222-222222222222",
    year_created: 2020,
    description: "Огненно-оранжевый гибискус с волнистым краем лепестков.",
    care_notes: "Много яркого света, тёплое содержание, регулярный полив.",
    main_photo_url: "/seed/ognenny-vikhr.svg",
    parent_a_id: null,
    parent_b_id: null,
    ...emptyPassport,
    origin: "Санкт-Петербург, Россия",
    bloom_type: "Полумахровый",
    size_range: "Крупный, 15–17 см",
    hybridizer: "Игорь Тропиков",
    date_registered: "2020-09-10",
    grower: "Игорь Тропиков",
    reg_mini: "Обычный (стандарт)",
    color_group: "Оранжевая",
    bloom_colors: "Огненно-оранжевый основной цвет с алыми мазками вдоль волнистого края и жёлтым горлом.",
  },
  {
    id: "bbbbbbb2-0000-0000-0000-000000000002",
    name: "Багряный Танец",
    species: "Махровый",
    breeder_id: "22222222-2222-2222-2222-222222222222",
    year_created: 2023,
    description: "Махровый багряный гибискус, потомок «Огненного Вихря».",
    care_notes: "Тепло, влажность, защита от прямого полуденного солнца.",
    main_photo_url: "/seed/bagryany-tanets.svg",
    parent_a_id: "bbbbbbb1-0000-0000-0000-000000000001",
    parent_b_id: null,
    ...emptyPassport,
    origin: "Санкт-Петербург, Россия",
    pod_parent: "Огненный Вихрь",
    bloom_type: "Махровый",
    size_range: "Очень крупный, 19–22 см",
    hybridizer: "Игорь Тропиков",
    date_registered: "2023-07-25",
    grower: "Игорь Тропиков",
    reg_mini: "Обычный (стандарт)",
    color_group: "Бордовая",
    propagation: "Черенкование",
    bloom_colors: "Глубокий багряный основной цвет с бархатистым тёмным горлом и тонкой серебристой каймой по гофрированному краю.",
  },
];

export const mockPhotos: Photo[] = [
  {
    id: "p1",
    variety_id: "aaaaaaa3-0000-0000-0000-000000000003",
    photo_url: "/seed/rozovaya-zarya.svg",
    caption: "Первое цветение",
  },
  {
    id: "p2",
    variety_id: "aaaaaaa3-0000-0000-0000-000000000003",
    photo_url: "/seed/rozovaya-zarya-2.svg",
    caption: "Крупный план",
  },
  {
    id: "p3",
    variety_id: "aaaaaaa3-0000-0000-0000-000000000003",
    photo_url: "/seed/rozovaya-zarya-3.svg",
    caption: "Махровая форма",
  },
  {
    id: "p4",
    variety_id: "bbbbbbb2-0000-0000-0000-000000000002",
    photo_url: "/seed/bagryany-tanets.svg",
    caption: "Махровое цветение",
  },
];

/** Текущий «залогиненный» селекционер для демо-режима без auth. */
export const DEMO_BREEDER_ID = "11111111-1111-1111-1111-111111111111";
